# Generated by Django 3.2.15 on 2023-04-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles_and_detail_payments', '0013_alter_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(blank=True, choices=[('Розхід', 'Розхід'), ('Прихід', 'Прихід')], max_length=50),
        ),
    ]
