# Generated by Django 3.2.15 on 2023-03-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('title_sec', models.CharField(blank=True, max_length=70)),
                ('short_text', models.CharField(max_length=200)),
                ('short_text_sec', models.CharField(blank=True, max_length=200)),
                ('image_director', models.ImageField(blank=True, null=True, upload_to='aboutUs/')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gallery.gallery', verbose_name='Галерея')),
            ],
        ),
        migrations.CreateModel(
            name='PageTarrif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_seo', models.CharField(max_length=50)),
                ('description_seo', models.CharField(max_length=250)),
                ('keywords_seo', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='TarrifForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='tarrif/')),
                ('title', models.CharField(max_length=50)),
                ('pageTarrif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Front_pages.pagetarrif', verbose_name='Тариф')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('seo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Front_pages.seoblock', verbose_name='СЕО Блок')),
            ],
        ),
        migrations.AddField(
            model_name='pagetarrif',
            name='seo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Front_pages.seoblock', verbose_name='СЕО Блок'),
        ),
        migrations.CreateModel(
            name='GeneralPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('short_text', models.CharField(max_length=270)),
                ('image1', models.ImageField(upload_to='GeneralPage/image')),
                ('image2', models.ImageField(upload_to='GeneralPage/image')),
                ('image3', models.ImageField(upload_to='GeneralPage/image')),
                ('seo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Front_pages.seoblock', verbose_name='СЕО Блок')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, upload_to='document/')),
                ('text', models.CharField(blank=True, max_length=100)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Front_pages.aboutus', verbose_name='ПроНас')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_text', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('fio', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('code_card', models.CharField(max_length=50)),
                ('seo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Front_pages.seoblock', verbose_name='СЕО Блок')),
            ],
        ),
        migrations.CreateModel(
            name='BlockAndServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blockAndServices')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('generalPage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Front_pages.generalpage', verbose_name='ГоловнаСторінка')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Front_pages.services', verbose_name='Послуги')),
            ],
        ),
        migrations.AddField(
            model_name='aboutus',
            name='seo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Front_pages.seoblock', verbose_name='СЕО Блок'),
        ),
    ]
