# Generated by Django 3.2.15 on 2023-05-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='short_text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='short_text_sec',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='blockandservices',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='blockandservices',
            name='image',
            field=models.ImageField(blank=True, upload_to='blockAndServices'),
        ),
        migrations.AlterField(
            model_name='blockandservices',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='short_text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='generalpage',
            name='image1',
            field=models.ImageField(blank=True, upload_to='GeneralPage/image'),
        ),
        migrations.AlterField(
            model_name='generalpage',
            name='image2',
            field=models.ImageField(blank=True, upload_to='GeneralPage/image'),
        ),
        migrations.AlterField(
            model_name='generalpage',
            name='image3',
            field=models.ImageField(blank=True, upload_to='GeneralPage/image'),
        ),
        migrations.AlterField(
            model_name='generalpage',
            name='short_text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='generalpage',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pagetarrif',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
