# Generated by Django 3.2.15 on 2023-05-17 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Articles_and_detail_payments', '0030_alter_article_type'),
        ('Personal_book', '0031_alter_personalbook_status'),
        ('Statement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Article', to='Articles_and_detail_payments.article', verbose_name='Стаття '),
        ),
        migrations.AddField(
            model_name='statement',
            name='personal_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PersonalBook', to='Personal_book.personalbook', verbose_name='ОсобистийРахунок'),
        ),
    ]
