# Generated by Django 3.2.15 on 2023-05-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statement', '0003_statement_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='sattus',
            field=models.CharField(choices=[('Не проведений', 'Не проведений'), ('Проведений', 'Проведений')], max_length=50, null=True),
        ),
    ]
