# Generated by Django 3.2.15 on 2023-05-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statement', '0005_auto_20230517_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='type',
            field=models.CharField(choices=[('Розхід', 'Розхід'), ('Прихід', 'Прихід')], max_length=50, null=True),
        ),
    ]
