# Generated by Django 3.2.15 on 2023-05-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statement', '0009_auto_20230517_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='status',
            field=models.CharField(blank=True, choices=[('Проведений', 'Проведений'), ('Не проведений', 'Не проведений')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='status_perfom',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='type',
            field=models.CharField(blank=True, choices=[('Розхід', 'Розхід'), ('Прихід', 'Прихід')], max_length=50, null=True),
        ),
    ]
