# Generated by Django 3.2.15 on 2023-05-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statement', '0012_auto_20230519_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='status',
            field=models.CharField(blank=True, choices=[('Не проведений', 'Не проведений'), ('Проведений', 'Проведений')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='type',
            field=models.CharField(blank=True, choices=[('Розхід', 'Розхід'), ('Прихід', 'Прихід')], max_length=50, null=True),
        ),
    ]
