# Generated by Django 3.2.15 on 2023-05-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Statement', '0013_auto_20230519_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='status',
            field=models.CharField(blank=True, choices=[('Проведений', 'Проведений'), ('Не проведений', 'Не проведений')], max_length=50, null=True),
        ),
    ]
