# Generated by Django 3.2.15 on 2023-05-24 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Statement', '0027_alter_statement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='ownerAppartemnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Owner_appartament', to=settings.AUTH_USER_MODEL, verbose_name='ВолодарКвартири'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='type',
            field=models.CharField(blank=True, choices=[('Розхід', 'Розхід'), ('Прихід', 'Прихід')], max_length=50, null=True),
        ),
    ]
