# Generated by Django 3.2.15 on 2023-03-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='status_pay',
            field=models.CharField(blank=True, choices=[(1000, 'Оплачена'), (3000, 'Неоплачена '), (2000, 'Частково оплачена'), (None, 'Оберіть...')], max_length=50),
        ),
    ]
