# Generated by Django 3.2.15 on 2023-05-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0041_alter_receipt_status_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='uid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='confirm',
            field=models.CharField(blank=True, choices=[('Не проведена', 'Не проведена'), ('Проведена', 'Проведена')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status_pay',
            field=models.CharField(blank=True, choices=[('Частково оплачена', 'Частково оплачена'), ('Оплачена', 'Оплачена'), ('Неоплачена', 'Неоплачена ')], max_length=50),
        ),
    ]
