# Generated by Django 3.2.15 on 2023-05-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0042_auto_20230516_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='date_created',
        ),
        migrations.AddField(
            model_name='receipt',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status_pay',
            field=models.CharField(blank=True, choices=[('Частково оплачена', 'Частково оплачена'), ('Неоплачена', 'Неоплачена '), ('Оплачена', 'Оплачена')], max_length=50),
        ),
    ]
