# Generated by Django 3.2.15 on 2023-05-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0044_alter_receipt_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='status_pay',
            field=models.CharField(blank=True, choices=[('Неоплачена', 'Неоплачена '), ('Оплачена', 'Оплачена'), ('Частково оплачена', 'Частково оплачена')], max_length=50),
        ),
    ]
