# Generated by Django 3.2.15 on 2023-05-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0046_auto_20230517_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='status_pay',
            field=models.CharField(blank=True, choices=[('Частково оплачена', 'Частково оплачена'), ('Оплачена', 'Оплачена'), ('Неоплачена', 'Неоплачена ')], max_length=50),
        ),
    ]
