# Generated by Django 3.2.15 on 2023-05-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0047_alter_receipt_status_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='confirm',
            field=models.CharField(blank=True, choices=[('Проведена', 'Проведена'), ('Не проведена', 'Не проведена')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status_pay',
            field=models.CharField(blank=True, choices=[('Частково оплачена', 'Частково оплачена'), ('Неоплачена', 'Неоплачена '), ('Оплачена', 'Оплачена')], max_length=50),
        ),
    ]
