# Generated by Django 3.2.15 on 2023-05-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0001_initial'),
        ('Receipt', '0048_auto_20230517_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='House.house', verbose_name='Будинок'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='House.section', verbose_name='Секція'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='confirm',
            field=models.CharField(blank=True, choices=[('Не проведена', 'Не проведена'), ('Проведена', 'Проведена')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status_pay',
            field=models.CharField(blank=True, choices=[('Неоплачена', 'Неоплачена '), ('Оплачена', 'Оплачена'), ('Частково оплачена', 'Частково оплачена')], max_length=50),
        ),
    ]
