# Generated by Django 3.2.15 on 2023-05-17 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_book', '0034_alter_personalbook_status'),
        ('Receipt', '0049_auto_20230517_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='personal_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Personal_book.personalbook', verbose_name='ОсобовийРахунок'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='confirm',
            field=models.CharField(blank=True, choices=[('Проведена', 'Проведена'), ('Не проведена', 'Не проведена')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status_pay',
            field=models.CharField(blank=True, choices=[('Частково оплачена', 'Частково оплачена'), ('Неоплачена', 'Неоплачена '), ('Оплачена', 'Оплачена')], max_length=50),
        ),
    ]
