# Generated by Django 3.2.15 on 2023-05-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0051_alter_receipt_status_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='confirm',
            field=models.CharField(blank=True, choices=[('Не проведена', 'Не проведена'), ('Проведена', 'Проведена')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status_pay',
            field=models.CharField(blank=True, choices=[('Оплачена', 'Оплачена'), ('Неоплачена', 'Неоплачена '), ('Частково оплачена', 'Частково оплачена')], max_length=50),
        ),
    ]
