# Generated by Django 3.2.15 on 2023-05-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0054_auto_20230519_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='status_pay',
            field=models.CharField(blank=True, choices=[('Оплачена', 'Оплачена'), ('Частково оплачена', 'Частково оплачена'), ('Неоплачена', 'Неоплачена ')], max_length=50),
        ),
    ]
