# Generated by Django 3.2.15 on 2023-05-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0057_alter_receipt_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
