# Generated by Django 3.2.15 on 2023-05-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0062_auto_20230521_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='confirm_text',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='confirm',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status_pay',
            field=models.CharField(blank=True, choices=[('Неоплачена', 'Неоплачена '), ('Оплачена', 'Оплачена'), ('Частково оплачена', 'Частково оплачена')], max_length=50),
        ),
    ]
