# Generated by Django 3.2.15 on 2023-05-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0063_auto_20230522_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='confirm_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status_pay',
            field=models.CharField(blank=True, choices=[('Частково оплачена', 'Частково оплачена'), ('Оплачена', 'Оплачена'), ('Неоплачена', 'Неоплачена ')], max_length=50),
        ),
    ]
