# Generated by Django 3.2.15 on 2023-05-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0064_auto_20230522_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='confirm_text',
            field=models.CharField(blank=True, choices=[('Проведена', 'Проведена'), ('Не проведена', 'Не проведена')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status_pay',
            field=models.CharField(blank=True, choices=[('Неоплачена', 'Неоплачена '), ('Частково оплачена', 'Частково оплачена'), ('Оплачена', 'Оплачена')], max_length=50),
        ),
    ]
