# Generated by Django 3.2.15 on 2023-05-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0068_auto_20230522_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='confirm_text',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status_pay',
            field=models.CharField(blank=True, choices=[('Неоплачена', 'Неоплачена '), ('Частково оплачена', 'Частково оплачена'), ('Оплачена', 'Оплачена')], max_length=50),
        ),
    ]
