# Generated by Django 3.2.15 on 2023-05-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0070_alter_receipt_status_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='status_pay',
            field=models.CharField(blank=True, choices=[('Частково оплачена', 'Частково оплачена'), ('Оплачена', 'Оплачена'), ('Неоплачена', 'Неоплачена')], max_length=50),
        ),
    ]
