version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/usr/src/app/
    ports:
      - "8080:8080"
    env_file:
      - .env
  db:
    image: postgres:15.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
volumes:
  postgres_data: