# Generated by Django 3.2.15 on 2023-03-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Appartament', '0001_initial'),
        ('House', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[(None, 'Активний'), (10000, 'Неактивний')], max_length=50)),
                ('appartament', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Appartament.appartament', verbose_name='Квартира')),
                ('house', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='House.house', verbose_name='Будинок')),
                ('section', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='House.section', verbose_name='Секція')),
            ],
        ),
    ]
