# Generated by Django 3.2.15 on 2023-05-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_book', '0014_personalbook_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalbook',
            name='residual',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='personalbook',
            name='status',
            field=models.CharField(blank=True, choices=[(10000, 'Неактивний'), (None, 'Активний')], max_length=50),
        ),
    ]
