# Generated by Django 3.2.15 on 2023-05-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appartament', '0001_initial'),
        ('Personal_book', '0022_alter_personalbook_residual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalbook',
            name='appartament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appartament.appartament', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='personalbook',
            name='residual',
            field=models.CharField(blank=True, choices=[('Є борг', 'Є борг'), ('Немає боргу', 'Немає боргу')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='personalbook',
            name='status',
            field=models.CharField(blank=True, choices=[('Неактивний', 'Неактивний'), ('Активний', 'Активний')], max_length=50),
        ),
    ]
