# Generated by Django 3.2.15 on 2023-05-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_book', '0031_alter_personalbook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalbook',
            name='status',
            field=models.CharField(blank=True, choices=[('Активний', 'Активний'), ('Неактивний', 'Неактивний')], max_length=50),
        ),
    ]
