# Generated by Django 3.2.15 on 2023-05-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_book', '0047_alter_personalbook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalbook',
            name='residual',
            field=models.CharField(blank=True, choices=[('Немає боргу', 'Немає боргу'), ('Є борг', 'Є борг')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='personalbook',
            name='status',
            field=models.CharField(blank=True, choices=[('Неактивний', 'Неактивний'), ('Активний', 'Активний')], max_length=50),
        ),
    ]
