# Generated by Django 3.2.15 on 2023-03-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatsterApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_problem', models.CharField(max_length=500)),
                ('comment', models.CharField(max_length=250)),
                ('typeMaster', models.CharField(blank=True, choices=[(10, 'Сантехник'), (30, 'Слюсар'), (None, ''), (20, 'Електрик')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[(20, 'В роботі'), (None, ''), (30, 'Виконано'), (10, 'Нове')], max_length=50)),
                ('name_master', models.CharField(max_length=50)),
                ('ownerAppartament', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='User.user', verbose_name='Володар квартири')),
            ],
        ),
    ]
