# Generated by Django 3.2.15 on 2023-03-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master_application', '0002_auto_20230328_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matsterapplication',
            name='status',
            field=models.CharField(blank=True, choices=[(10, 'Нове'), (None, ''), (30, 'Виконано'), (20, 'В роботі')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matsterapplication',
            name='typeMaster',
            field=models.CharField(blank=True, choices=[(30, 'Слюсар'), (None, ''), (20, 'Електрик'), (10, 'Сантехник')], max_length=50, null=True),
        ),
    ]
