# Generated by Django 3.2.15 on 2023-03-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master_application', '0004_auto_20230328_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matsterapplication',
            name='status',
            field=models.CharField(blank=True, choices=[(20, 'В роботі'), (10, 'Нове'), (30, 'Виконано'), (None, '')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matsterapplication',
            name='typeMaster',
            field=models.CharField(blank=True, choices=[(30, 'Слюсар'), (None, ''), (10, 'Сантехник'), (20, 'Електрик')], max_length=50, null=True),
        ),
    ]
