# Generated by Django 3.2.15 on 2023-04-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master_application', '0012_alter_matsterapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matsterapplication',
            name='status',
            field=models.CharField(blank=True, choices=[(30, 'Виконано'), (10, 'Нове'), (20, 'В роботі'), (None, '')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matsterapplication',
            name='typeMaster',
            field=models.CharField(blank=True, choices=[(10, 'Сантехник'), (20, 'Електрик'), (None, ''), (30, 'Слюсар')], max_length=50, null=True),
        ),
    ]
