# Generated by Django 3.2.15 on 2023-04-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master_application', '0013_auto_20230402_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matsterapplication',
            name='status',
            field=models.CharField(blank=True, choices=[(20, 'В роботі'), (30, 'Виконано'), (None, ''), (10, 'Нове')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matsterapplication',
            name='typeMaster',
            field=models.CharField(blank=True, choices=[(10, 'Сантехник'), (None, ''), (20, 'Електрик'), (30, 'Слюсар')], max_length=50, null=True),
        ),
    ]
