# Generated by Django 3.2.15 on 2023-04-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master_application', '0015_auto_20230410_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matsterapplication',
            name='status',
            field=models.CharField(blank=True, choices=[(30, 'Виконано'), (10, 'Нове'), (20, 'В роботі'), (None, '')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matsterapplication',
            name='typeMaster',
            field=models.CharField(blank=True, choices=[(30, 'Слюсар'), (20, 'Електрик'), (10, 'Сантехник'), (None, '')], max_length=50, null=True),
        ),
    ]
