# Generated by Django 3.2.15 on 2023-04-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master_application', '0016_auto_20230411_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matsterapplication',
            name='status',
            field=models.CharField(blank=True, choices=[(20, 'В роботі'), (30, 'Виконано'), (None, ''), (10, 'Нове')], max_length=50),
        ),
    ]
