# Generated by Django 3.2.15 on 2023-04-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_user_uid'),
        ('Master_application', '0017_alter_matsterapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matsterapplication',
            name='name_master',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matsterapplication',
            name='status',
            field=models.CharField(blank=True, choices=[(20, 'В роботі'), (10, 'Нове'), (None, ''), (30, 'Виконано')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matsterapplication',
            name='typeMaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.role'),
        ),
    ]
