# Generated by Django 3.2.15 on 2023-04-14 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appartament', '0001_initial'),
        ('Master_application', '0018_auto_20230414_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='matsterapplication',
            name='appartament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appartament.appartament', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='matsterapplication',
            name='status',
            field=models.CharField(blank=True, choices=[(30, 'Виконано'), (10, 'Нове'), (20, 'В роботі'), (None, '')], max_length=50),
        ),
    ]
