# Generated by Django 3.2.15 on 2023-04-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master_application', '0019_auto_20230414_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matsterapplication',
            name='status',
            field=models.CharField(blank=True, choices=[(20, 'В роботі'), (10, 'Нове'), (30, 'Виконано')], max_length=50),
        ),
    ]
