# Generated by Django 3.2.15 on 2023-04-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master_application', '0021_alter_matsterapplication_name_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matsterapplication',
            name='status',
            field=models.CharField(blank=True, choices=[(30, 'Виконано'), (10, 'Нове'), (None, None), (20, 'В роботі')], max_length=50),
        ),
    ]
