# Generated by Django 3.2.15 on 2023-04-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master_application', '0023_alter_matsterapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matsterapplication',
            name='status',
            field=models.CharField(blank=True, choices=[(20, 'В роботі'), (30, 'Виконано'), (10, 'Нове')], max_length=50),
        ),
    ]
