# Generated by Django 3.2.15 on 2023-04-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master_application', '0025_auto_20230415_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matsterapplication',
            name='status',
            field=models.CharField(blank=True, choices=[(30, 'Виконано'), (10, 'Нове'), (20, 'В роботі')], max_length=50),
        ),
    ]
