# Generated by Django 3.2.15 on 2023-05-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master_application', '0071_alter_matsterapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matsterapplication',
            name='status',
            field=models.CharField(blank=True, choices=[('В роботі', 'В роботі'), ('Виконано', 'Виконано'), ('Нове', 'Нове')], max_length=50),
        ),
    ]
