# Generated by Django 3.2.15 on 2023-03-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tarrif_and_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meters_data', models.CharField(max_length=50)),
                ('date_published', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('meter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Tarrif_and_services.service', verbose_name='Лічильник')),
            ],
        ),
    ]
