# Generated by Django 3.2.15 on 2023-04-29 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appartament', '0001_initial'),
        ('Tarrif_and_services', '0001_initial'),
        ('House', '0001_initial'),
        ('Meters_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metersdata',
            name='appartament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appartament.appartament', verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='metersdata',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='House.house', verbose_name='Будинок'),
        ),
        migrations.AddField(
            model_name='metersdata',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='House.section', verbose_name='Секція'),
        ),
        migrations.AlterField(
            model_name='metersdata',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tarrif_and_services.service', verbose_name='Лічильник'),
        ),
    ]
