# Generated by Django 3.2.15 on 2023-05-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meters_data', '0002_auto_20230429_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='metersdata',
            name='uid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
