# Generated by Django 3.2.15 on 2023-05-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meters_data', '0010_alter_metersdata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metersdata',
            name='status',
            field=models.CharField(choices=[('Нульове', 'Нульове'), ('Нове', 'Нове'), ('Враховано та заплачено', 'Враховано та заплачено'), ('Враховано', 'Враховано')], max_length=50),
        ),
    ]
