# Generated by Django 3.2.15 on 2023-05-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meters_data', '0034_alter_metersdata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metersdata',
            name='status',
            field=models.CharField(choices=[('Нове', 'Нове'), ('Враховано та заплачено', 'Враховано та заплачено'), ('Враховано', 'Враховано'), ('Нульове', 'Нульове')], max_length=50),
        ),
    ]
