# Generated by Django 3.2.15 on 2023-05-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meters_data', '0044_alter_metersdata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metersdata',
            name='status',
            field=models.CharField(choices=[('Враховано', 'Враховано'), ('Нове', 'Нове'), ('Нульове', 'Нульове'), ('Враховано та заплачено', 'Враховано та заплачено')], max_length=50),
        ),
    ]
