# Generated by Django 3.2.15 on 2023-05-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarrif_and_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefortariif',
            name='consum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
