# Generated by Django 3.2.15 on 2023-03-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('House', '0001_initial'),
        ('Tarrif_and_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_appartament', models.IntegerField()),
                ('area', models.IntegerField()),
                ('floor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='House.floor', verbose_name='Поверх')),
                ('house', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='House.house', verbose_name='Будинок')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='User.user', verbose_name='Власник')),
                ('section', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='House.section', verbose_name='Секція')),
                ('tarrif', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Tarrif_and_services.tarrif', verbose_name='Тариф')),
            ],
        ),
    ]
