# Generated by Django 3.2.15 on 2023-05-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appartament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartament',
            name='personal_book',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
