# Generated by Django 3.2.15 on 2023-05-25 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_book', '0055_auto_20230525_0948'),
        ('Appartament', '0002_appartament_personal_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartament',
            name='personal_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PERI', to='Personal_book.personalbook', verbose_name='ОсобистийРахунок'),
        ),
    ]
