# Generated by Django 3.2.15 on 2023-03-28 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('director', models.BooleanField()),
                ('manager', models.BooleanField()),
                ('booker', models.BooleanField()),
                ('electrician', models.BooleanField()),
                ('plumber', models.BooleanField()),
                ('slusar', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='middle_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('logo', models.ImageField(blank=True, upload_to='user/logo/', verbose_name='logo')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='phone_number')),
                ('viber', models.IntegerField(blank=True, null=True, verbose_name='viber')),
                ('telegram', models.CharField(blank=True, max_length=250, null=True, verbose_name='telegram')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('status', models.BooleanField(null=True, verbose_name='status')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.role', verbose_name='Роль')),
            ],
        ),
    ]
