# Generated by Django 3.2.15 on 2023-04-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20230329_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(choices=[('1000', 'Активний'), ('2000', 'Новий'), ('3000', 'Неактивний')], null=True, verbose_name='status'),
        ),
    ]
