# Generated by Django 3.2.15 on 2023-04-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(choices=[(1000, 'Активний'), (2000, 'Новий'), (3000, 'Неактивний')], null=True, verbose_name='status'),
        ),
    ]
