# Generated by Django 3.2.15 on 2023-04-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Активний', '1000'), ('Новий', '2000'), ('Неактивний', '3000')], max_length=50, null=True, verbose_name='status'),
        ),
    ]
