# Generated by Django 3.2.15 on 2023-04-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_user_about_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
